name: build-marp-slides

on:
  push:
    paths:
      - "**.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli

      - name: Build slides
        run: marp slides.md -o slides.html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: trabalhos_academicos
          path: trabalhos_academicos.html
