name: build slides

on:
  push:
    paths:
      - "**.md"
  workflow_dispatch:

jobs:
  marp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Marp build
        uses: marp-team/marp-cli-action@v3
        with:
          args: trabalhos_academicos.md -o trabalhos_academicos.html
